
services:
  autoclean:
    build: .
    image: autoclean:latest
    volumes:
      # These paths will be mounted to fixed locations in the container
      - ${EEG_DATA_PATH:-./data}:/data
      - ${CONFIG_PATH:-./configs}:/app/configs
      - ${OUTPUT_PATH:-./output}:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    shm_size: '1gb'
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    # Example commands:

  review:
    build:
      context: .
      dockerfile: Dockerfile.review
    image: autoclean-review:latest
    volumes:
      - /mnt/srv2/RAWDATA/1_NBRT_LAB_STUDIES/Raw_P1_EEGs_n141/Autoclean_output_testing2/:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - QT_QPA_PLATFORM=xcb
    ports:
      - 6080:6080     # noVNC web interface
