site_name: AutoClean Pipeline
site_description: Automated EEG Processing Pipeline Documentation
site_url: https://github.com/ernie-ecs/autoclean_pipeline
repo_name: ernie-ecs/autoclean_pipeline
repo_url: https://github.com/ernie-ecs/autoclean_pipeline

theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - overrides/stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_if_no_docstring: false
            show_root_heading: true
            show_root_toc_entry: true
            heading_level: 2

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ernie-ecs/autoclean_pipeline
  generator: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Pipeline Overview: user-guide/pipeline-overview.md
    - Tasks: user-guide/tasks.md
    - Step Functions: user-guide/step-functions.md
    - Configuration Files: user-guide/configuration-files.md
    - Plugin System: plugin_system.md
    - Troubleshooting: user-guide/troubleshooting.md
  - API Reference:
    - Pipeline: api-reference/pipeline.md
    - Task: api-reference/task.md
    - Step Functions: api-reference/step-functions.md
    - Signal Processing Mixins: api-reference/signal-processing-mixins.md
    - Reporting Mixins: api-reference/reporting-mixins.md
    - Utils: api-reference/utils.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md 