# AutoClean Configuration File with Event Processor Settings

# General pipeline settings
verbose: true
task: "p300"  # Can be "p300", "hbcd_mmn", "resting", etc.

# Processing Steps Configuration
# Set to false to disable specific processing steps
processing_steps:
  resample_step: true
  eog_step: true
  reference_step: true
  trim_step: true
  crop_step: true
  
  # Event processing master toggle
  event_processing_step: true

# Event Processor Specific Configuration

# P300 Event Processor Settings
p300_event_processing: true
p300_event_mapping:
  "13": "Standard"
  "14": "Target"
  "15": "Novel"  # Optional additional event type

# HBCD MMN Event Processor Settings
hbcd_mmn_event_processing: true
hbcd_mmn_event_columns:
  - "Task"
  - "type"
  - "onset"
  - "Condition"
  - "Duration"  # Optional additional column
hbcd_mmn_description_format: "{Task}/{type}/{Condition}"

# Resting State Event Processor Settings
resting_state_event_processing: true
resting_state_condition: "eyes_open"  # Can be "eyes_open" or "eyes_closed"
resting_state_description_format: "resting_state/{condition}"

# Optional: Create segments for resting state data
resting_state_create_segments: true
resting_state_segment_duration: 5.0  # In seconds
resting_state_segment_description: "segment"
