# =================================================================
# AUTOCLEAN CONFIGURATION FILE
# This file controls how EEG data is automatically processed and cleaned
# =================================================================

# TASK CONFIGURATION
# Each task represents a different type of EEG recording (e.g., resting state, specific experiments)
tasks:
  # RESTING STATE TASK (Eyes Open)
  RestingEyesOpen:
    mne_task: "rest"
    description: "Resting state with eyes open"
    lossless_config: configs/pylossless/lossless_config.yaml    # Points to additional configuration settings
    settings:
      # PROCESSING STEPS
      # Each step can be enabled/disabled and has specific settings
      
      resample_step:
        enabled: false        # Set to false to skip this step
        value: 250          # New sampling rate in Hz
      
      drop_outerlayer:
        enabled: false
        value: []

      eog_step:
        enabled: false
        value: [1, 32, 8, 14, 17, 21, 25, 125, 126, 127, 128]  # Channel numbers for eye movement detection
      
      trim_step:
        enabled: true
        value: 4            # Number of seconds to trim from start/end
      
      crop_step:
        enabled: true
        value:
          start: 0          # Start time in seconds
          end: 60         # null means use entire recording, or specify time in seconds (e.g., 30.0)
      
      reference_step:
        enabled: false
        value: "average"    # Type of EEG reference to use
      
      montage:
        enabled: true
        value: "GSN-HydroCel-129"  # Type of EEG cap/electrode layout

      event_id:
        enabled: false      # No triggers in resting state
        value: {}          # Empty since no triggers

      epoch_settings:
        enabled: true     
        value:
          tmin: -1
          tmax: 1
        remove_baseline:
          enabled: false
          window: [null, 0]
        threshold_rejection:
          enabled: false
          volt_threshold: 
            eeg: 150e-6
    # ARTIFACT REJECTION SETTINGS
    rejection_policy:
      ch_flags_to_reject: ["noisy", "uncorrelated"]  # Types of bad channels to reject
      ch_cleaning_mode: "interpolate"                           # How to handle bad channels
      interpolate_bads_kwargs:
        method: "spline"                                    # Method for interpolating bad channels
      ic_flags_to_reject: ["muscle", "heart", "eog", "ch_noise", "line_noise"]  # Types of components to reject
      ic_rejection_threshold: 0.3                              # Threshold for component rejection
      remove_flagged_ics: true          # Whether to remove marked components
                            
  
  RestingEyesOpenRev:
    mne_task: "rest"
    description: "Resting state with eyes open"
    lossless_config: configs/pylossless/lossless_config.yaml    # Points to additional configuration settings
    settings:
      # PROCESSING STEPS
      # Each step can be enabled/disabled and has specific settings
      
      resample_step:
        enabled: true        # Set to false to skip this step
        value: 250          # New sampling rate in Hz
      
      drop_outerlayer:
        enabled: false
        value: []

      eog_step:
        enabled: false
        value: [1, 32, 8, 14, 17, 21, 25, 125, 126, 127, 128]  # Channel numbers for eye movement detection
      
      trim_step:
        enabled: true
        value: 4            # Number of seconds to trim from start/end
      
      crop_step:
        enabled: true
        value:
          start: 0          # Start time in seconds
          end: 60         # null means use entire recording, or specify time in seconds (e.g., 30.0)
      
      reference_step:
        enabled: false
        value: "average"    # Type of EEG reference to use
      
      montage:
        enabled: true
        value: "GSN-HydroCel-129"  # Type of EEG cap/electrode layout

      event_id:
        enabled: false      # No triggers in resting state
        value: {}          # Empty since no triggers

      epoch_settings:
        enabled: true     
        value:
          tmin: -1
          tmax: 1
        remove_baseline:
          enabled: false
          window: [null, 0]
        threshold_rejection:
          enabled: false
          volt_threshold: 
            eeg: 150e-6

    # ARTIFACT REJECTION SETTINGS
    rejection_policy:
      ch_flags_to_reject: ["noisy", "uncorrelated"]  # Types of bad channels to reject
      ch_cleaning_mode: "interpolate"                           # How to handle bad channels
      interpolate_bads_kwargs:
        method: "spline"                                    # Method for interpolating bad channels
      ic_flags_to_reject: ["muscle", "heart", "eog", "ch_noise", "line_noise"]  # Types of components to reject
      ic_rejection_threshold: 0.3                              # Threshold for component rejection
      remove_flagged_ics: true          # Whether to remove marked components
                            
  
  ChirpDefault:
    mne_task: "chirp"
    description: "Chirp auditory stimulus task" 
    lossless_config: configs/pylossless/lossless_config_chirp.yaml
    settings:
      resample_step:
        enabled: true
        value: 250
      drop_outerlayer:
        enabled: false
        value: ["E17", "E38", "E43", "E44", "E48", "E49", "E113", "E114", "E119",
                "E120", "E121", "E56", "E63", "E68", "E73", "E81", "E88", "E94",
                "E99", "E107" ]
      eog_step:
        enabled: false
        value: [1, 32, 8, 14, 17, 21, 25, 125, 126, 127, 128]
      trim_step:
        enabled: true
        value: 4
      crop_step:
        enabled: false
        value:
          start: 0
          end: 60  # null uses full duration
      reference_step:
        enabled: false
        value: "average"
      montage:
        enabled: true
        value: "GSN-HydroCel-129"
      event_id:
        enabled: true
        value: {'DIN8'}
      epoch_settings:
        enabled: true
        value:
          tmin: -0.5
          tmax: 2.5
        remove_baseline:
          enabled: false
          window: [null, 0]
        threshold_rejection:
          enabled: false
          volt_threshold: 
            eeg: 150e-6
    rejection_policy:
      ch_flags_to_reject: ["noisy", "uncorrelated"]
      ch_cleaning_mode: "interpolate"
      interpolate_bads_kwargs:
        method: "spline"
      ic_flags_to_reject: ["muscle", "heart", "eog", "ch_noise", "line_noise"]
      ic_rejection_threshold: 0.3
      remove_flagged_ics: true
  
  AssrDefault:
    mne_task: "assr"
    description: "Auditory steady state response task"
    lossless_config: configs/pylossless/lossless_config.yaml
    settings:
      resample_step:
        enabled: true
        value: 250
      drop_outerlayer:
        enabled: false
        value: []
      eog_step:
        enabled: false
        value: [1, 32, 8, 14, 17, 21, 25, 125, 126, 127, 128]
      trim_step:
        enabled: true
        value: 4
      crop_step:
        enabled: true
        value:
          start: 0
          end: null  # null uses full duration
      reference_step:
        enabled: false
        value: "average"
      montage:
        enabled: true
        value: "GSN-HydroCel-129"
      event_id:
        enabled: true
        value: {'DI66': 1}
      epoch_settings:
        enabled: true
        value:
          tmin: -0.5
          tmax: 2.7
        remove_baseline:
          enabled: false
          window: [null, 0]
        threshold_rejection:
          enabled: false
          volt_threshold: 
            eeg: 150e-6
    rejection_policy:
      ch_flags_to_reject: ["noisy", "uncorrelated", "bridged"]
      ch_cleaning_mode: "interpolate"
      interpolate_bads_kwargs:
        method: "spline"
      ic_flags_to_reject: ["muscle", "heart", "eog", "ch_noise", "line_noise"]
      ic_rejection_threshold: 0.3
      remove_flagged_ics: true

  BB_Long:
    mne_task: "Binural Beats"
    description: "Binural Beats full length file"
    lossless_config: configs/pylossless/lossless_config.yaml
    settings:
      resample_step:
        enabled: true
        value: 250
      drop_outerlayer:
        enabled: false
        value: []
      eog_step:
        enabled: false
        value: [1, 32, 8, 14, 17, 21, 25, 125, 126, 127, 128]
      trim_step:
        enabled: true
        value: 1
      crop_step:
        enabled: false
        value:
          start: 0
          end: null  # null uses full duration
      reference_step:
        enabled: false
        value: "average"
      montage:
        enabled: true
        value: "GSN-HydroCel-129"
      event_id:
        enabled: false
        value: {}
      epoch_settings:
        enabled: false
        value:
          tmin: -0.5
          tmax: 2.7
        remove_baseline:
          enabled: false
          window: [null, 0]
        threshold_rejection:
          enabled: false
          volt_threshold: 
            eeg: 150e-6
    rejection_policy:
      ch_flags_to_reject: ["noisy", "uncorrelated", "bridged"]
      ch_cleaning_mode: "interpolate"
      interpolate_bads_kwargs:
        method: "spline"
      ic_flags_to_reject: ["muscle", "heart", "eog", "ch_noise", "line_noise"]
      ic_rejection_threshold: 0.3
      remove_flagged_ics: true
  
  HBCD_MMN:
    mne_task: "MMN"
    description: "HBCD Mismatch Negativity task"
    lossless_config: configs/pylossless/lossless_config_hbcd.yaml
    settings:
      resample_step:
        enabled: true
        value: 1000
      drop_outerlayer:
        enabled: true
        value: ["E17", "E38", "E43", "E44", "E48", "E49", "E113", "E114", "E119",
                "E120", "E121", "E56", "E63", "E68", "E73", "E81", "E88", "E94",
                "E99", "E107" ]
      eog_step:
        enabled: false
        value: []
      trim_step:
        enabled: true
        value: 4
      crop_step:
        enabled: false
        value:
          start: 0
          end: 60 # null uses full duration
      reference_step:
        enabled: true
        value: ["E129"]
      montage:
        enabled: true
        value: "GSN-HydroCel-124"
      event_id:
        enabled: true
        value: {'DIN2'}
      epoch_settings:
        enabled: true
        value:
          tmin: -0.1
          tmax: 0.5
        remove_baseline: #Remove/Correct baseline
          enabled: true
          window: [null, 0]
        threshold_rejection: #Remove artifact laden epoch based on voltage threshold
          enabled: true
          volt_threshold: 
            eeg: 200e-6

    rejection_policy:
      ch_flags_to_reject: ["noisy", "uncorrelated"]
      ch_cleaning_mode: "interpolate"
      interpolate_bads_kwargs:
        method: "spline"
      ic_flags_to_reject: ["muscle", "heart", "eog", "ch_noise", "line_noise"]
      ic_rejection_threshold: 0.3
      remove_flagged_ics: true  

# OUTPUT FILE CONFIGURATION
# Controls which processing stages save intermediate files
# Useful for quality checking and troubleshooting
stage_files:
  post_import:
    enabled: true          # Set to true to save file after this stage
    suffix: "_postimport"  # This text will be added to the filename

  post_prepipeline:
    enabled: true
    suffix: "_postprepipeline"

  #Prepipeline steps
  post_resample:
    enabled: true
    suffix: "_postresample"

  post_outerlayer:
    enabled: false
    suffix: "_postouterlayer"

  post_reference:
    enabled: false
    suffix: "_postreference"

  post_trim:
    enabled: false
    suffix: "_posttrim"

  post_crop:
    enabled: false
    suffix: "_postcrop"

  #PyLossless steps
  post_pylossless:
    enabled: true
    suffix: "_postpylossless"

  post_bad_channels:
    enabled: false
    suffix: "_postbadchannels"

  post_artifact_detection:
    enabled: true
    suffix: "_postartifactdetection"

  post_rejection_policy:
    enabled: true
    suffix: "_postrejection"

  #Epochs steps
  post_epochs:
    enabled: true
    suffix: "_postepochs"

  post_gfp_clean:
    enabled: true
    suffix: "_postgfpclean"

  post_autoreject:
    enabled: true
    suffix: "_postautoreject"

  post_comp:
    enabled: true
    suffix: "_postcomp"

  post_edit:
    enabled: true
    suffix: "_postedit"

