name: Deploy Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-material-extensions mkdocs-glightbox mkdocs-git-revision-date-localized-plugin mkdocstrings-python

      - name: Deploy Documentation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdocs gh-deploy --force 