   name: Build and Deploy Docs
   
   on:
     push:
       branches: [main]
   
   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - name: Set up Python
           uses: actions/setup-python@v4
           with:
             python-version: '3.10'
         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install -e .
             pip install sphinx sphinx_rtd_theme numpydoc sphinx.ext.autodoc sphinx.ext.autosummary sphinx.ext.intersphinx sphinx.ext.viewcode pydata-sphinx-theme
         - name: Build docs
           run: |
             cd sphinx_example/docs
             make html
         - name: Deploy
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./sphinx_example/docs/_build/html